version: '2'

services:
  web:
    context: .
    dockerfile: Dockerfile.prod
    command: gunicorn testing_platform.wsgi:application --bind 0.0.0.0:8000 -t 12000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 12345:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
