version: '3.3'

services:
  web:
    build:
      context: ./LangExBank
      dockerfile: new.Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env.prod
    depends_on:
      - db
    # entrypoint: ./entrypoint.sh # For initial set-up
    command: gunicorn testing_platform.wsgi:application --bind 0.0.0.0:8000 -t 500000 # For later launches
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./env.prod
  reference_platform:
    build:
      context: ./reference_platform
      dockerfile: Dockerfile
    command: uwsgi --master --http 0.0.0.0:8000 --wsgi-file app.py --callable application --static-map /reference_platform/static=/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./env.prod
    volumes:
      - reference_volume:/usr/src/app/reference_data
  distractor_selector:
    image: niklogin/disselector:latest
    expose:
      - 5000
    command: python -m api

volumes:
  static_volume:
  media_volume:
  postgres_volume:
  reference_volume:

