# Generated by Django 2.1.3 on 2018-11-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('question_type', models.CharField(max_length=20)),
                ('question_level', models.SmallIntegerField()),
                ('error_tag', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Question')),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Quizz')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=20)),
                ('rights', models.CharField(choices=[('A', 'Admin'), ('S', 'Student'), ('T', 'Teacher')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.User')),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='quizz',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(to='main_app.Quizz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Question'),
        ),
        migrations.AddField(
            model_name='results',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Student'),
        ),
    ]
