# Generated by Django 2.1.3 on 2018-12-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(null=True, to='main_app.Quizz'),
        ),
    ]
