# Generated by Django 2.2.2 on 2019-07-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181219_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='strip_answers',
            field=models.BooleanField(null=True),
        ),
    ]
