# Generated by Django 2.2.2 on 2019-08-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190826_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
