# Generated by Django 2.2.2 on 2019-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20191122_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
