# Generated by Django 2.2.2 on 2019-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('L', 'Listening'), ('R', 'Reading'), ('W', 'Writing')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='supplement',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
