# Generated by Django 2.2.2 on 2019-11-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20191124_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ielts_test',
            name='full_grade',
            field=models.FloatField(null=True),
        ),
    ]
