# Generated by Django 2.2.2 on 2020-01-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_ielts_test_full_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ukey',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
