# Generated by Django 3.0.6 on 2020-05-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_question_case_insensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='wronganswer',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Question'),
        ),
    ]
