# Generated by Django 3.0.6 on 2020-09-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTSWritingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('text', models.CharField(max_length=100000)),
                ('supplement', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IELTSWritingResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.IELTSWritingTask')),
            ],
        ),
    ]
