# Generated by Django 3.0.6 on 2020-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_ieltswritingresponse_ieltswritingtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltswritingresponse',
            name='mark',
            field=models.FloatField(null=True),
        ),
    ]
