# Generated by Django 3.0.6 on 2021-03-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20210106_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multi_field',
            field=models.BooleanField(default=False),
        ),
    ]
