# Generated by Django 2.2.2 on 2019-11-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190826_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='IELTS_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('section_type', models.CharField(choices=[('L', 'Listening'), ('R', 'Reading'), ('W', 'Writing')], max_length=1)),
                ('supplement', models.FileField(upload_to='C:\\Users\\k1l77\\realec-testing-platform-project-master\\media\\')),
                ('supplement_type', models.CharField(choices=[('p', 'pdf'), ('i', 'image'), ('a', 'audio')], max_length=1, null=True)),
                ('ielts_test', models.ManyToManyField(blank=True, to='main_app.IELTS_Test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Section'),
        ),
    ]
