# Generated by Django 2.2.2 on 2019-11-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20191120_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.CharField(max_length=100000),
        ),
    ]
