# Generated by Django 2.2.2 on 2019-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20191120_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='error_tag',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
