# Generated by Django 2.2.2 on 2019-11-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_section_supplement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='supplement',
            field=models.FileField(null=True, upload_to='C:\\Users\\k1l77\\realec-testing-platform-project-master\\media\\'),
        ),
    ]
