# Generated by Django 2.2.2 on 2020-01-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_wronganswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wronganswer',
            old_name='question_id',
            new_name='question',
        ),
    ]
