# Generated by Django 2.2.2 on 2020-02-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20200122_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='case_insensitive',
            field=models.BooleanField(default=False),
        ),
    ]
