# Generated by Django 3.0.6 on 2020-10-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20201005_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltswritingresponse',
            name='text',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
