# Generated by Django 3.1.2 on 2021-01-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_ieltswritingresponse_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ielts_test',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ieltswritingresponse',
            name='submission_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ieltswritingtask',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ielts_test',
            name='collection',
            field=models.ManyToManyField(blank=True, to='main_app.TestCollection'),
        ),
        migrations.AddField(
            model_name='ieltswritingtask',
            name='collection',
            field=models.ManyToManyField(blank=True, to='main_app.TestCollection'),
        ),
    ]
