# Generated by Django 4.0.3 on 2022-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_question_multi_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='allow_reference',
            field=models.BooleanField(default=False),
        ),
    ]
