# Generated by Django 3.2.13 on 2022-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_quizz_allow_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(),
        ),
    ]
