# Generated by Django 3.2.13 on 2022-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_alter_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wronganswer',
            name='distractor_model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
