# Generated by Django 3.2.13 on 2022-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_wronganswer_distractor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch_elem_id',
            field=models.IntegerField(null=True),
        ),
    ]
